name: deploy

on:
  push:
    branches: [main]

concurrency:
   group: "pages"
   cancel-in-progress: true

jobs:
  documentation:
    name: GitHub Pages
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      pages: write
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Generate
        run: |
          make doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
